module.exports = {
	221: "Santander Empresas",
	218: "Itaú Empresas",
	217: "Banco do Brasil Empresas",
	209: "Bradesco Empresas",
	216: "Caixa Econômica Federal Empresas",
	227: "Sicredi Empresas",
	609: "Bradesco Empresas [OF]",
	616: "Caixa Econômica Federal Empresas [OF]",
	618: "Itaú Empresas [OF]",
	621: "Santander Empresas [OF]",
	627: "Sicredi Empresas [OF]",
	628: "Sicoob Empresas [OF]",
	655: "BTG Pactual Empresas [OF]",
	660: "Banrisul Empresas [OF]",
	662: "Banco do Brasil Empresas [OF]",
	664: "Nubank Empresas [OF]",
	665: "Mercado Pago Empresas [OF]",
	666: "Banco BMG Empresas [OF]",
	670: "Unicred Empresas [OF]",
	672: "Banco do Nordeste do Brasil Empresas [OF]",
	697: "Safra Empresas [OF]",
	702: "XP Banking Empresas [OF]",
	706: "Banco Paulista Empresas [OF]",
	718: "BV - Corporate [OF]",
	778: "InfinitePay Empresas [OF]",
};